Transition to the fdcan-rs crate
stm32-rs/stm32g4xx-hal pull request #39
Opened 2021-12-13 10:39 UTC by luctius

As discussed in #34, the FDCAN part has been transitioned to a new crate. This PR uses that crate instead of our own implementation.

2023-02-12 21:56 UTC, kevswims commented
@luctius is there anything I can do to help get this in? I have a board with an STM32g4 and 2 CAN transceivers on it that I can do testing on if needed. At the moment I am using a super hacky driver in my own code to get the CAN working but I would love to move to this if possible.

2023-02-13 08:24 UTC, luctius commented
I've updated this to fdcan 0.1.2. It builds; but if you have time I would mind if you could check that everything still works.

2023-02-14 03:45 UTC, kevswims requested changes
I made some changes to the example itself to get this going on my hardware and I was able to get the the two channels on my board to talk to each other. Functionally, I think this is good to go in.

I can put up a follow-on PR that cleans up the example to allow running it either on physical hardware or in loopback mode for testing. I should be able to get that up in a day or two.

2023-02-14 03:45 UTC, kevswims commented on Cargo.toml
> +# git = "https://github.com/stm32-rs/fdcan.git"
Probably don't want to merge with these commented bits in here.

2023-02-14 03:45 UTC, kevswims commented on src/lib.rs
> +// pub mod fdcan;
Remove commented code?

2023-02-15 11:12 UTC, merged